## Use Github Actions to build sailfishos rpms
## Copy from https://github.com/CODeRUS/screencast
## Thanks CODeRUS

name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  RELEASE: 3.4.0.24

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Prepare
      run: mkdir output && git submodule update --init

    - name: Build armv7hl
      run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /share/* . ;
            mb2 -t SailfishOS-$RELEASE-armv7hl build ;
            sudo cp -r RPMS/*.rpm /share/output"

    - name: Build i486
      run: docker run --rm --privileged -v $PWD:/share coderus/sailfishos-platform-sdk:$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /share/* . ;
            mb2 -t SailfishOS-$RELEASE-i486 build ;
            sudo cp -r RPMS/*.rpm /share/output"

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: harbour-sailfishclub-rpms.zip
        path: output
